#!/usr/bin/expect

set timeout -1

spawn python3 clue.py

expect "Welcome to Clue!"
expect "Enter the order of the players, separated by commas."
send -- "sc, mu, pe\r"
expect "Enter the CPU suspect(['Scarlett', 'Mustard', 'Peacock']):"
send -- "sc\r"
expect "Enter the card the CPU has (1):"
send -- "kn\r"
expect "Enter the card the CPU has (2):"
send -- "bil\r"
expect "Enter the card the CPU has (3):"
send -- "rev\r"
expect "Enter the card the CPU has (4):"
send -- "whi\r"
expect "Enter the card the CPU has (5):"
send -- "hall\r"
expect "Enter the card the CPU has (6):"
send -- "con\r"
expect "Enter the dice roll for Scarlett:"
send -- "10\r"
expect "Did Mustard reveal a card to you (y/n)?"
send -- "y\r"
expect "Enter the card Mustard revealed:"
send -- "can\r"
expect "Did Peacock reveal a card to Mustard (y/n)?"
send -- "y\r"
expect "Did Scarlett reveal a card to Peacock (y/n)?"
send -- "n\r"
expect "Did Mustard reveal a card to Peacock (y/n)?"
send -- "y\r"
expect "Enter the dice roll for Scarlett:"
send -- "12\r"
expect "Did Mustard reveal a card to you (y/n)?"
send -- "y\r"
expect "Enter the card Mustard revealed:"
send -- "wren\r"
expect "Did Peacock reveal a card to Mustard (y/n)?"
send -- "n\r"
expect "Did Scarlett reveal a card to Mustard (y/n)?"
send -- "y\r"
expect "Did Scarlett reveal a card to Peacock (y/n)?"
send -- "y\r"
expect "Enter the dice roll for Scarlett:"
send -- "10\r"
expect "Did Mustard reveal a card to you (y/n)?"
send -- "n\r"
expect "Did Peacock reveal a card to you (y/n)?"
send -- "y\r"
expect "Enter the card Peacock revealed:"
send -- "must\r"
expect "Did Peacock reveal a card to Mustard (y/n)?"
send -- "y\r"
expect "Did Scarlett reveal a card to Peacock (y/n)?"
send -- "y\r"
expect "Enter the dice roll for Scarlett:"
send -- "12\r"
expect "Did Mustard reveal a card to you (y/n)?"
send -- "n\r"
expect "Did Peacock reveal a card to you (y/n)?"
send -- "n\r"
expect "Did Peacock reveal a card to Mustard (y/n)?"
send -- "n\r"
expect "Did Scarlett reveal a card to Mustard (y/n)?"
send -- "n\r"
expect "Did Scarlett reveal a card to Peacock (y/n)?"
send -- "n\r"
expect "Did Mustard reveal a card to Peacock (y/n)?"
send -- "n\r"

# After the scripted inputs, allow interacting with the program.
interact
